### ISSUE TITLE
How to set up a specific Google Chrome browser. like puppeteer.launch({   executablePath: path.normalize(windowsPath)})

### ISSUE THREAD

**Issue by Kaer663** [ultimateakash/puppeteer-html-pdf#10]
I didn't find the corresponding setting in the documentation

full code
    const windowsPath =  'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';
    const browser = await puppeteer.launch({
      executablePath: path.normalize(windowsPath),
     });

**Comment by ultimateakash** [comment]
Hello @Kaer663,

I've just released patch version 4.0.3. You can find more details in the documentation.

**Comment by ultimateakash** [comment]
@Kaer663 
The path you provided for **executablePath** is missing the necessary escaping for backslashes. In JavaScript strings, backslashes are escape characters, so you need to use double backslashes.
`const windowsPath = 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';`

**Comment by Kaer663** [comment]
> @Kaer663 The path you provided for **executablePath** is missing the necessary escaping for backslashes. In JavaScript strings, backslashes are escape characters, so you need to use double backslashes. `const windowsPath = 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';`

Thank you for your reply
I didn’t write it all here
full code

```javascript
    // const windowsPath =
    //   'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';
    // const browser = await puppeteer.launch({
    //   executablePath: path.normalize(windowsPath),
    // });
    // const page = await browser.newPage();
    // await page.setContent(htmlStr, { waitUntil: 'networkidle0' });
    // await page.pdf({ path: outPath, format: 'A4' });
    // await browser.close();

```
Thank you very much for your reminder as well
