### ISSUE TITLE
How i can run puppteer PDF functionality with node js alpine image on ubuntu environment

### ISSUE THREAD

**Issue by anantjain06** [ultimateakash/puppeteer-html-pdf#13]
Please provide docker commands to run PDF functionality on linux with alpine

**Comment by ultimateakash** [comment]
Hello @anantjain06 

I have tested with the following Dockerfile. it's working properly.
### Dockerfile
```
# Use Node.js Alpine as the base image
FROM node:alpine

# Install necessary dependencies for Puppeteer
RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    freetype-dev \
    harfbuzz \
    ca-certificates \
    ttf-freefont

    
# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install npm dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose the port your app runs on
EXPOSE 3000

# Command to run your application
CMD ["npm", "start"]
```
You need to pass `executablePath` in `setOptions()` method

### Sample Code
```js
const PuppeteerHTMLPDF = require('puppeteer-html-pdf');

exports.printPDF = async (req, res) => {

  const htmlPDF = new PuppeteerHTMLPDF();

  htmlPDF.setOptions({
    executablePath: '/usr/bin/chromium-browser',
    format: 'A4'
  });

  const content = '<h1>the future is black</h1>';

  try {
    const pdfBuffer = await htmlPDF.create(content);
    res.attachment('invoice.pdf')
    res.end(pdfBuffer);
  } catch (error) {
    console.log('PuppeteerHTMLPDF error', error);
  }
}
```

**Comment by imxaander** [comment]
Works fine.

**Comment by anantjain06** [comment]
Issue still persists

I have used same dependencies in my docker file on ubuntu environment

Alpine image version :   FROM node:14.17.6-alpine

# Install necessary dependencies
 for Puppeteer
RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    freetype-dev \
    harfbuzz \
    ca-certificates \
    ttf-freefont
    
    In NODE JS i am using below code
    
    const htmlPDF = new PuppeteerHTMLPDF();
            const htmloptions = {
                executablePath: '/usr/bin/chromium-browser',
                format: "A4",
                path: config.filepath + newFilename, // you can pass path to save the file
                headless: false
              };
              htmlPDF.setOptions(htmloptions);
              const htmlPdfContent = html;
                try {
                    console.log("PDF PRINTED")
                    //await htmlPDF.create(htmlPdfContent);
                    htmlPDF.create(htmlPdfContent, (err, result) => {
                        if (err) {
                            logger.log(err, constants.logLevels.ERROR);
                            deferred.reject(err);
                        } else {
                            console.log(result)
                            deferred.resolve({ filePath: config.apiUrl + '/' + newFilename, fileName: newFilename });
                        }
                    });
                   
                } catch (error) {
                    console.log("PuppeteerHTMLPDF error", error);
             }
    
    
    It is showing nothing on server console and not printing any PDF and loader is continuously spinning
    
    
    and same code is working fine on my windows machine.
