### ISSUE TITLE
ERROR :: Do not know how to load path: node_modules/yargs/yargs

### ISSUE THREAD

**Issue by MadhavGutte** [ultimateakash/puppeteer-html-pdf#15]
[ERROR] Do not know how to load path: node_modules/yargs/yargs

    node_modules/@puppeteer/browsers/lib/cjs/CLI.js:39:40:
      39 │ const yargs_1 = __importDefault(require("yargs/yargs"));

**Comment by ultimateakash** [comment]
Hello @MadhavGutte,

Could you please delete your `node_modules` folder and install it again? If the problem persists, try cleaning your npm cache.

First, run these commands to remove `node_modules` and reinstall the dependencies:

```sh
rm -rf node_modules
npm install
```

If that doesn't resolve the issue, clean your npm cache with this command:

```sh
npm cache clean --force
```

Let me know if you need further assistance!

**Comment by MadhavGutte** [comment]
Thanks for your help!
