### ISSUE TITLE
Font Family on Header & Footer

### ISSUE THREAD

**Issue by YosaRama** [ultimateakash/puppeteer-html-pdf#18]
I was enable Header & Footer display on option, then I create Header & Footer HTML and embed it on option. I want to use custom Font Family on my Header & Footer, but every time try to include Font Source it will face `Protocol Error`

any suggestion to handle this issue?

**Comment by ultimateakash** [comment]
Hi @YosaRama ,

Could you please share the code snippet where you are setting up the header and footer HTML with the font source? This will help us understand the issue better and provide a more accurate solution.

Thanks!

**Comment by YosaRama** [comment]
Hi @ultimateakash, Thanks for your response

just give you preview of my project, my project build on Next.js 14 Framework
here how I use `puppeteer-html-pdf`

![Screenshot 2024-07-10 at 12 03 26](https://github.com/ultimateakash/puppeteer-html-pdf/assets/67961793/884ade26-ca20-4318-a516-34cfe3bf43bd)

and here my header HTML look like
![Screenshot 2024-07-10 at 12 05 02](https://github.com/ultimateakash/puppeteer-html-pdf/assets/67961793/9fcd4b88-4ed7-4c33-b37d-bf7faa7acfaa)

I already try with Base64, Local File, also it's not working

Thanks!

**Comment by YosaRama** [comment]
Hi @ultimateakash, is there any update for this?

**Comment by ultimateakash** [comment]
Hi @YosaRama ,

I apologize for the delayed response. I've thoroughly investigated the issue with using custom font families in headers and footers with Puppeteer, and unfortunately, it appears that Puppeteer itself has limitations when it comes to including font sources directly due to protocol errors.

Based on my findings, various methods such as using Base64 encoding or local files have also not been successful in resolving this issue.

If you're still looking for a workaround, one potential approach could involve pre-rendering the headers and footers with the desired fonts using another tool or service before passing them to Puppeteer for PDF generation.

**Comment by YosaRama** [comment]
Hi @ultimateakash no worries about that!

Okay I see, I need to using another tool or service before passing them to Puppeteer yaa, is there any recommendation tool or service for this?

**Comment by ultimateakash** [comment]
Hi @YosaRama,

You can check out `node-wkhtmltopdf` for your PDF generation. It could be a good solution for your needs.

**Comment by YosaRama** [comment]
Hi @ultimateakash, 

what is the expectation using `node-wkhtmltopdf`, could you elaborate more for me?

**Comment by ultimateakash** [comment]
Hello @YosaRama,

You can use google fonts/remote URL with wkhtmltopdf.  you'll need to install the wkhtmltopdf library on your system and configure the PATH environment variable.

http://wkhtmltopdf.org/downloads.html#stable

Here is the full example.
### index.js
```js
const express = require('express');
const wkhtmltopdf = require('wkhtmltopdf');
const fs = require('fs').promises;
const hbs = require('hbs');
const path = require('path');

const app = express();

// Function to render a Handlebars template with data
const renderTemplate = async (templatePath, data) => {
  try {
    const template = await fs.readFile(templatePath, 'utf8');
    const compiledTemplate = hbs.compile(template);
    return compiledTemplate(data);
  } catch (error) {
    console.error("Error reading template file:", error);
    throw error;
  }
};

// Serve header HTML
app.get('/header', async (req, res) => {
  const headerPath = path.join(__dirname, './header.hbs');
  const headerHtml = await renderTemplate(headerPath, {});
  res.send(headerHtml);
});

// Serve footer HTML
app.get('/footer', async (req, res) => {
  const footerPath = path.join(__dirname, './footer.hbs');
  const footerHtml = await renderTemplate(footerPath, {});
  res.send(footerHtml);
});

// Generate and serve PDF
app.get('/print', async (req, res) => {
  try {
    const contentPath = path.join(__dirname, './invoice.hbs');
    const contentHtml = await renderTemplate(contentPath, {});

    // Generate PDF with wkhtmltopdf
    wkhtmltopdf(contentHtml, {
      headerHtml: 'http://localhost:3000/header',
      footerHtml: 'http://localhost:3000/footer',
      marginTop: '10mm',
      marginBottom: '10mm',
      pageSize: 'A4',
      noStopSlowScripts: true,
      javascriptDelay: 10000, // Increased delay in milliseconds
      debug: true, // Enable debug
      loadErrorHandling: 'ignore' // Ignore loading errors
    }).pipe(res);
  } catch (error) {
    console.error("Error during PDF generation:", error);
    res.status(500).send('Something went wrong.');
  }
});

// Start the server
app.listen(3000, () => {
  console.log('Server is running on http://localhost:3000');
});
```
### invoice.hbs
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Crimson+Pro:ital,wght@0,200..900;1,200..900&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Crimson Pro', serif;
            font-size: 14px;
        }
    </style>
</head>
<body>
    <h1>Main Content</h1>
    <p>Hello, world!</p>
</body>
</html>
```

### header.hbs
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Crimson+Pro:ital,wght@0,200..900;1,200..900&display=swap" rel="stylesheet">
    <style>
        .header {
            font-family: 'Crimson Pro', serif;
            font-size: 12px;
        }
    </style>
</head>
<body>
    <div class="header">
        Your Header Content Here
    </div>
</body>
</html>
```

### footer.hbs
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Crimson+Pro:ital,wght@0,200..900;1,200..900&display=swap" rel="stylesheet">
    <style>
        .footer {
            font-family: 'Crimson Pro', serif;
            font-size: 12px;
        }
    </style>
</head>
<body>
    <div class="footer">
        Your Footer Content Here
    </div>
</body>
</html>
```

### wkhtmltopdf
https://www.npmjs.com/package/wkhtmltopdf

### output
[print.pdf](https://github.com/user-attachments/files/16480702/print.pdf)
