### ISSUE TITLE
[Question] Conditional header content?

### ISSUE THREAD

**Issue by Ben-CA** [ultimateakash/puppeteer-html-pdf#3]
Is there any way to provide conditional header content?

In my case, I want a logo and an invoice #, etc. at the top of every page.

On the first page, I want shipping details.

On subsequent pages, a partial header, but no shipping details.

I can see how to achieve headers and footers, but is there a way to set a portion of a header as "conditional" - such that it only shows on page 1?

Alternatively, is there any method to paginate before generation?

**Comment by ultimateakash** [comment]
Hello @Ben-CA, 

Conditional rendering of specific content in the header based on the page number is not directly supported within Puppeteer's header/footer API.

However, you can implement a workaround by splitting your HTML into pages(using `page-break-before` property) before generating the PDF. 
```html
    <div>
        <h1>Page 1 (with shipping details and a complete header)</h1>
    </div>
    <div style="page-break-before: always;">
      <h1>Page 2 (with a partial header and no shipping details)</h1>
    </div>
    <div style="page-break-before: always;">
      <h1>Page 3 (with a partial header and no shipping details)</h1>
    </div>
```
No need to use `headerTemplate` property.

**Comment by ultimateakash** [comment]
@Ben-CA, `puppeteer-html-pdf version 3` also supports browser control. you can generate separate PDF files and merge those files into single PDF using `pdf-lib`
```js
const PuppeteerHTMLPDF = require('puppeteer-html-pdf');
const { PDFDocument } = require('pdf-lib');

const createPDF = async () => {
  const htmlPDF = new PuppeteerHTMLPDF();
  const options = {
    format: 'A4'
  }
  htmlPDF.setOptions(options);

  const content1 = '<div>Page 1 (with shipping details and a complete header)</div>'; 
  const content2 = '<div>Other Pages (with a partial header and no shipping details)</div>'; 
  
  try {
    htmlPDF.setAutoCloseBrowser(false)
    const pdfBuffer1 = await htmlPDF.create(content1); 
    const pdfBuffer2 = await htmlPDF.create(content2); 

    const firstPage = await PDFDocument.load(pdfBuffer1);
    const otherPages = await PDFDocument.load(pdfBuffer2);
  
    // Add subsequent pages to the first page
    for (let i = 0; i < otherPages.getPageCount(); i++) {
      const [copiedPage] = await firstPage.copyPages(otherPages, [i]);
      firstPage.addPage(copiedPage);
    }
  
    const mergedPdfBuffer = await firstPage.save();

    const filePath = `${__dirname}/shipping.pdf`
    await htmlPDF.writeFile(mergedPdfBuffer, filePath);
  } catch (error) {
    console.log('PuppeteerHTMLPDF error', error);
  }
  finally {
    await htmlPDF.closeBrowser();
  }
}

createPDF();
```

**Comment by Ben-CA** [comment]
Thank you for the responses! I'll have to see if I can make either of those approaches work for this.

It's one of those things that "seem simple" until you start digging into it, and then there's a lot of complex dynamic requirements.
