### ISSUE TITLE
deprecated puppeteer@19.11.1: < 21.8.0 is no longer supported

### ISSUE THREAD

**Issue by vignesh-s** [ultimateakash/puppeteer-html-pdf#6]
getting warning `deprecated puppeteer@19.11.1: < 21.8.0 is no longer supported`

**Comment by ultimateakash** [comment]
https://github.com/ultimateakash/puppeteer-html-pdf/pull/7 
Please uninstall and install the latest version.
V4.0.0

**Comment by vignesh-s** [comment]
Thanks for the Update 👍🏼
