### ISSUE TITLE
React 18

### ISSUE THREAD

**Issue by Danny-Nunez** [ultimateakash/puppeteer-html-pdf#9]
Is there a plan to get this package to work with react 18 with out needing to use npm legacy peers.

**Comment by ultimateakash** [comment]
Thanks for raising this concern about compatibility with React 18. Currently, the puppeteer-html-pdf library is designed to work on the backend side

If you're looking to create PDFs from HTML in your React application, you might find html2pdf.js to be a suitable alternative:

[html2pdf.js](https://www.npmjs.com/package/html2pdf.js)

Feel free to explore this option for your PDF generation needs.

Best regards,

**Comment by Danny-Nunez** [comment]
I’ve tried deploying repo as a backend on vercel. I keep getting method not allowed but when testing locally works fine. Is there a recommended server for this puppeteer to html work properly Sent from my iPhoneOn Apr 14, 2024, at 5:32 AM, Akash Kumar Verma ***@***.***> wrote:﻿
Thanks for raising this concern about compatibility with React 18. Currently, the puppeteer-html-pdf library is designed to work on the backend side
If you're looking to create PDFs from HTML in your React application, you might find html2pdf.js to be a suitable alternative:
html2pdf.js
Feel free to explore this option for your PDF generation needs.
Best regards,

**Comment by ultimateakash** [comment]
Hi @Danny-Nunez,

The `method not allowed` error might be related to the HTTP method used or the server configuration on Vercel.

You might find platforms like DigitalOcean or AWS with an nginx server to be more suitable for deploying your Node.js backend.
